// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrkucXpG7nFX6ZEyIwAneojfyeH-zeO8',
    appId: '1:306926818437:web:6661c42548e5919472c5ec',
    messagingSenderId: '306926818437',
    projectId: 'chatapp-18e44',
    authDomain: 'chatapp-18e44.firebaseapp.com',
    storageBucket: 'chatapp-18e44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPf8EJ7Wy3NUT0ehP9YYE12SS1S6Zy5w',
    appId: '1:306926818437:android:2f04737e95f462d072c5ec',
    messagingSenderId: '306926818437',
    projectId: 'chatapp-18e44',
    storageBucket: 'chatapp-18e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOLhYcz443Fu9k6OmQVy3ALDCdzhlpQE',
    appId: '1:306926818437:ios:f8c93370594ab48972c5ec',
    messagingSenderId: '306926818437',
    projectId: 'chatapp-18e44',
    storageBucket: 'chatapp-18e44.appspot.com',
    iosBundleId: 'com.kolink.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeOLhYcz443Fu9k6OmQVy3ALDCdzhlpQE',
    appId: '1:306926818437:ios:839ffca4d018a5ab72c5ec',
    messagingSenderId: '306926818437',
    projectId: 'chatapp-18e44',
    storageBucket: 'chatapp-18e44.appspot.com',
    iosBundleId: 'com.kolink.chatapp.RunnerTests',
  );
}
